# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bitkumo - Cloud hosting for hackers
email: hello@bitkumo.com
description: Bitkumo scraps expensive support and passes the savings on to you. Built for hackers, by hackers. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bitkumo.com" # the base hostname & protocol for your site
twitter_username: getbitkumo
github_username:  bitkumo
timezone: America/New_York

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [vendor]

kramdown:
    input: GFM
